### ISSUE TITLE
Define CLI params

### ISSUE THREAD

**Issue by mkatsanto** [zavolanlab/zarp-cli#1]
Overview of the parameters that need to be implemented in the zarp-cli.
The concept is that the only mandatory ones are the sample inputs (in all their possible formats: paths, filenames, tables, sra codes, etc)

Category/Group | Option | Comment | Level
-- | -- | -- | --
Sample files | --sample-name | Useful to have meaningful name in results and to tell apart multilane samples | Main wrapper
  | --fq1 or positional argument | str (path) or [list] in case of multilane | Main wrapper
  | --fq2 or positional argument | str (path) or [list] in case of multilane | Main wrapper
  | --sample-table <samples.tsv> or positional argument  | This will contain all the sample related features | Main wrapper
  | --sra <SRR1> <SRR2> or positional argument | Search SRA? GEO? | SRA wrapper /GEO
  | --sample-path or positional argument | Take all samples from specified folder.In that case we should force user to use specific extensions for mate1 mate2, no multilanes will be allowed |  
Output directory | --out-dir | Output directory where intermediate files (e.g. config), results and reports will be generated | optional
HTSinfer | --htsinfer | Organism, Orientation, Adapters? (only 3p supported for now) |  
Sample features (contained in samples table if provided) | --mate1-direction | Overwrite --infer or check if compatible with --inferSalmon naming compatibility  forpaired-single, sense antisense combinations | HTSinfer?
  | --mate2-direction |  
  | --fq1-5p |   |  
  | --fq1-3p | HTSinfer support
  | --fq2-5p |  
  | --fq2-3p |  
  | --fragment-length-mean |   |  
  | --fragment-length-sd |   |  
  | --organism | Overwrite --infer or check if compatible with --inferIf different organisms are used, trigger a warning that this affects the analysis steps | HTSinfer
  | --trim-polya | default False |  
  | --gtf | Path or API fetch | Resources wrapper
  | --genome | Path or API fetch | Resources wrapper
Mapping | --multimappers | 100 (for STAR) | Main wrapper
  | --soft-clip | ['EndToEnd', 'Local']Default: EndToEnd | Main wrapper
  | --pass-mode | ["None", "Basic"]Default | Main wrapper
Snakemake execution | --keep-temp: default False | keep temporary folders or not | Main wrapper
  | --dry-run | Run up to step11 of zarp-app |  
CPUs | --cores |   | Main wrapper
Execution libraries | --use-singularity with--singularity-args |   | Main wrapper
  | --use-conda |   | Main wrapper
Execution environments | --cluster --local | cluster.json or (https://github.com/snakemake-profiles)For inferring execution parameters | Main wrapper
Reports | --no-report | Get both reports by default | Main wrapper
  | --run-description |   | Main wrapper
  | --run-identifier |   |  
  | --logo | Keep zavolab ones as default, if they are specified replace them. | Main wrapper
  | --url | Keep zavolab ones as default, if they are specified replace them. | Main wrapper
  | --author |   | Main wrapper
  | --author-email |   |  
  | --snakemake-report |   | Main wrapper
Config | --init | Always set to True if ~/.zarp/defaults.yaml is not available, otherwise default is False | Main wrapper

**Comment by mkatsanto** [comment]
Better to have this separately in the `config/cli.py`

**Comment by uniqueg** [comment]
Just some comments/opinions (I might add on to these later):

* I think FASTQ files should be passed as positional parameters _only_ (so no `--fq1`, `--fq2`, `--sra`, etc.)
* I would not implement `--sample-path` (better named `--sample-directory`), at least for now, because it cannot be implemented cleanly without some assumptions on sample names and there is relatively little added value (using positional arguments for passing files, one could just do `zarp /path/to/my/sample/dir/*fq`, which is more powerful because it doesn't need those assumptions on sample names); more importantly, for paired-end libraries things get really messy, unless a completely arbitrary naming scheme is assumed and enforced for mate files; and finding mates automatically with, e.g., pairwise checks with HTSinfer is not feasible with more than a few files because of the increasing number of combinations
* Instead of `--mate-1-direction` and `--mate-2-direction` I would use a parameter `read-orientation` and expect a string in Salmon notation. These should cover both single- and paired-end libraries if I'm not mistaken, so no need for two params
* I would use only one param `--adapter-3p` instead of `--fq1-3p` and `--fq2-3p` and allow supplying different adapters for mate files via a comma; this would be consistent with the proposed way of specifying mates of a paired-end library as positional args and also a cleaner/easier CLI interface
* I would not implement params (or _a_ param) for 5p adapters right now, because with the version of HTSinfer that we will have, there will be no support for that; I think it's okay as it's rarely used (I don't think we need it much in the lab, if ever); we can handle adapters more smartly in a future version
* I realized there is no default specified for STAR's two-pass mode option
* In general, I think for a tool's parameters (e.g., STAR align ends types and two-pass mode), we should always use the tools' defaults for any params that we make available to the user to change, because this is what users would expect. And by making them available for the users to change, we should suppose that changing them makes sense in the context of ZARP (otherwise we should _not_ make them available to the user to change). If we do want to use some more reasonable defaults (from our experience), the mechanism to set this up is by modifying the defaults during ZARP-cli init.
* An option `--htsinfer` is probably not necessary, as it will only be run for missing required parameters. _Not_ running inference would then lead to an error. If anything we could add a parameter `--no-inference`. Another question is how we want to pass params to HTSinfer. We could either interface these directly or, perhaps better, implement a `--config-file` param in HTSinfer and then pass any params through ZARP-cli via a single parameter `--htsinfer-config`.
* Perhaps we should discuss if (and if so, how) we should let the user pass through arguments for Snakemake and HTSinfer parameters in general. We might, for example, use the same approach we have prototyped for passing parameters to Snakemake rules.
* I think rather than have `--use-conda` and `--use-singularity` we should have something like `--tool-packaging` with options Conda (default) and Singularity. This would be easier than to manage multiple params, especially if there will be others in the future (e.g., Docker). Or possibly we could get away with using just a single parameter `--containerized_execution` to use Singularity or Docker by default (and which would be decided by the execution profile).
* Similarly, `--local` and `--cluster` seem somewhat arbitrary to me and could be bundled together. But perhaps we will first need to figure out how to use execution profiles (goes for the previous point, too).
* In addition to `--dry-run` (which would tell the user which samples were registered, how much data would need to be downloaded and which params would need to be inferred), I think an option `--prepare-run` would be useful in which data is downloaded, missing parameters are inferred and ZARP inputs/configs are prepared, but ZARP is not started. Even better, have a single parameter `execution_mode` that can take one of the choices `dry-run`, `prepare-run` and `run` (default).
* I would not include `--snakemake-report` and only allow users to disable both types of reports with `--no-report` (if at all).
* For `--keep-temp`, we should perhaps think if there's a chance that there's going to be more fine-grained control in the future. If so, having a flag is a bad design choice, as it is not open to extension (it only has two states). So if we cannot rule out extensions in the future, I would propose to have a parameter `--keep-files` (or `--delete-files`) that can take different (and possibly multiple) values such as `results`, `temporary`, `logs`, `all` etc.

**Comment by uniqueg** [comment]
I have built the models based on the table in the issue description, but incorporating my suggestions from the comment above in [this file](https://github.com/zavolanlab/zarp-cli/blob/db4a438be3cc5bbe2f091d7c64cc2b0cd84dcf58/zarp/config/models.py). Would be good if people could have a look at my suggestions as well as the derived models ASAP, so that @mkatsanto can update the CLI params table and start implementing argument parser and I can add documentation and validations to the models.

**Comment by mkatsanto** [comment]
Some sample specific parameters have been eliminated. See:
- https://git.scicore.unibas.ch/zavolan_group/pipelines/zarp/-/issues/158
- https://git.scicore.unibas.ch/zavolan_group/pipelines/zarp/-/issues/160 in ZARP. 
Should propagate these changes here.

**Comment by uniqueg** [comment]
Note that HTSinfer will now be called in ZARP itself, so HTSinfer-specific parameters may have to be reinterpreted (might still make sense to use them and pass them to ZARP, but this needs some thinking)

**Comment by uniqueg** [comment]
To make clearer, how ZARP-cli is supposed to work, this would be the basic usage:

```bash
# zarp local single-end library
zarp my_single_end_sample.fastq.gz

# zarp local paired-end library
zarp my_first_mate.fastq.gz,my_second_mate.fastq.gz

# zarp multiple local libraries
zarp my_single_end_sample.fastq.gz my_first_mate.fastq.gz,my_second_mate.fastq.gz

# zarp library stored on SRA
zarp SRR10690190

# zarp both local and remote (SRA) libraries
zarp my_single_end_sample.fastq.gz SRR10690190

# zarp sample with non-default public resources
zarp -g GRCh38.100 SRR10690190

# zarp multiple samples in batch mode
zarp -t my_sample_table

# zarp everything at once
zarp \
    -t my_sample_table \
    -t my_other_sample_table \
    my_single_end_sample.fastq.gz \
    my_first_mate.fastq.gz,my_second_mate.fastq.gz \
    SRR10690190
```

And some ideas for future features:

```bash
# zarp sample and automatically push results RO-Crate to Zenodo
zarp --publish my_single_end_sample.fastq.gz

# zarp samples described in a LabKey table
zarp -t labkey:my_labkey_table
```
