### ISSUE TITLE
Move run specific parameters from samples.tsv to rule_config.yaml

### ISSUE THREAD

**Issue by ninsch3000** [zavolanlab/zarp-cli#19]
Related to #10; Same as [this issue](https://git.scicore.unibas.ch/zavolan_group/pipelines/zarp/-/issues/158)

The current layout of ZARP requires several parameters to be specified in the `samples.tsv` file, that should rather be specified in the recently introduced `rule_config.yaml` as they apply to all samples of a run.

Necessary changes in
- [ ] samples.tsv
- [ ]  rule_config.yaml  
- [ ] Snakefile, single/paired-end Snakefile, and consequently **ZARP**. Corresponding issue [here](https://git.scicore.unibas.ch/zavolan_group/pipelines/zarp/-/issues/158)

Suggestions from [ZARP #155](https://git.scicore.unibas.ch/zavolan_group/pipelines/zarp/-/issues/155) :   
single_end.snakefile.smk/paired_end.snakefile.smk/rule_config:
- map_genome_star: -- twopassMode
- map_genome_star: --alignEndsType
Corresponding samples.tsv columns
- pass_mode
- soft_clip

**Comment by ninsch3000** [comment]
This issue serves as a reminder for @uniqueg  which files to create in zarp-cli

**Comment by uniqueg** [comment]
The rule config is just passed as is. A default can be set (optionally), and it can be overridden on the command line for any given run. When no default is set and the CLI argument is not specified, no rule config is used.

Whether the sample table format, as currently implemented, is affected by these changes, we will see. But surely that part of ZARP-cli was implemented _after_ this issue was opened, so likely it will not diverge (much).
